baseURL = "https://amazing-torvalds-45cce3.netlify.com/"
languageCode = "en-us"
title = "Isak Nywall"
theme = "hugo-base"

[params]
  description = "I <3 making web site"
  mainIcon = "/img/hugo.png"
